In [25]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import joblib

In [26]:
df = pd.read_csv("student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [28]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [32]:
df['alc'] = (df['Dalc'] + df['Walc']) / 2

In [33]:
df.drop(columns=['Dalc','Walc','famrel','famsize','address','school',
    'sex','Pstatus','Mjob','Fjob','reason','guardian',
    'schoolsup','famsup','paid','activities','nursery','romantic'],axis=1,inplace=True)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         395 non-null    int64
 1   Medu        395 non-null    int64
 2   Fedu        395 non-null    int64
 3   traveltime  395 non-null    int64
 4   studytime   395 non-null    int64
 5   failures    395 non-null    int64
 6   higher      395 non-null    object
 7   internet    395 non-null    object
 8   freetime    395 non-null    int64
 9   goout       395 non-null    int64
 10  health      395 non-null    int64
 11  absences    395 non-null    int64
 12  G1          395 non-null    int64
 13  G2          395 non-null    int64
 14  G3          395 non-null    int64
 15  alc         395 non-null    float64
dtypes: float64(1), int64(13), object(2)
memory usage: 49.5+ KB

In [35]:
df['internet'].unique()

array(['no', 'yes'], dtype=object)

In [36]:
df['health'].unique()

array([3, 5, 1, 2, 4])

In [37]:
df['internet'] = df['internet'].map({'yes':1,'no':0})
df['higher'] = df['higher'].map({'yes':1,'no':0})

df = pd.get_dummies(df,drop_first=True)

In [38]:
X = df.drop('G3',axis=1)
y = df['G3']

In [39]:
X

,age,Medu,Fedu,traveltime,studytime,failures,higher,internet,freetime,goout,health,absences,G1,G2,alc
0,18,4,4,2,2,0,1,0,3,4,3,6,5,6,1.0
1,17,1,1,1,2,0,1,1,3,3,3,4,5,5,1.0
2,15,1,1,1,2,3,1,1,3,2,3,10,7,8,2.5
3,15,4,2,1,3,0,1,1,2,2,5,2,15,14,1.0
4,16,3,3,1,2,0,1,0,3,2,5,4,6,10,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,20,2,2,1,2,2,1,0,5,4,4,11,9,9,4.5
391,17,3,1,2,1,0,1,1,4,5,2,3,14,16,3.5
392,21,1,1,1,1,3,1,0,5,3,3,3,10,8,3.0
393,18,3,2,3,1,0,1,1,4,1,5,0,11,12,3.5
394,19,1,1,1,1,0,1,1,2,3,5,5,8,9,3.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         395 non-null    int64
 1   Medu        395 non-null    int64
 2   Fedu        395 non-null    int64
 3   traveltime  395 non-null    int64
 4   studytime   395 non-null    int64
 5   failures    395 non-null    int64
 6   higher      395 non-null    int64
 7   internet    395 non-null    int64
 8   freetime    395 non-null    int64
 9   goout       395 non-null    int64
 10  health      395 non-null    int64
 11  absences    395 non-null    int64
 12  G1          395 non-null    int64
 13  G2          395 non-null    int64
 14  G3          395 non-null    int64
 15  alc         395 non-null    float64
dtypes: float64(1), int64(15)
memory usage: 49.5 KB

In [41]:
X

,age,Medu,Fedu,traveltime,studytime,failures,higher,internet,freetime,goout,health,absences,G1,G2,alc
0,18,4,4,2,2,0,1,0,3,4,3,6,5,6,1.0
1,17,1,1,1,2,0,1,1,3,3,3,4,5,5,1.0
2,15,1,1,1,2,3,1,1,3,2,3,10,7,8,2.5
3,15,4,2,1,3,0,1,1,2,2,5,2,15,14,1.0
4,16,3,3,1,2,0,1,0,3,2,5,4,6,10,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,20,2,2,1,2,2,1,0,5,4,4,11,9,9,4.5
391,17,3,1,2,1,0,1,1,4,5,2,3,14,16,3.5
392,21,1,1,1,1,3,1,0,5,3,3,3,10,8,3.0
393,18,3,2,3,1,0,1,1,4,1,5,0,11,12,3.5
394,19,1,1,1,1,0,1,1,2,3,5,5,8,9,3.0

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [44]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
model = RandomForestRegressor(n_estimators=100,max_depth=5,random_state=42)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [45]:
y_pred

array([ 8.35202238, 11.84825479,  6.08302084,  9.24817895,  8.99877693,
       12.87894908, 18.829829  ,  6.82915875,  4.70997745, 13.35468673,
       15.48616314,  6.99656304, 14.06644804, 11.60877842, 14.22429316,
        8.42157222,  3.09798134, 10.83808871, 15.33445674,  3.99930669,
       14.11251553, 15.76198269, 15.273913  ,  6.73373934,  8.35895523,
       18.74542832, 10.59210494,  9.24314998, 18.0508582 , 10.72549392,
        8.95280036,  8.77503731, 15.38744181, 13.13543071,  3.30349397,
        5.9858726 ,  0.1375    , 15.13744147, 11.63408817,  8.83640032,
        6.00478939, 10.55483639, 14.09771195,  9.06935563, 15.15067165,
        9.42291222, 11.56866612, 14.20146492, 12.96199933, 15.36189746,
       13.36415201, 15.31129319, 10.69686198,  8.96737036,  5.72456074,
       12.98148704, 10.49570007,  2.33400044, 15.45128591, 16.00184782,
       13.40330453,  9.29773987,  8.48391477,  5.61447352,  7.18964932,
       18.14126515,  9.00478374,  9.94768648,  9.59036762, 15.39532636,
        8.6204105 ,  9.98524397, 13.57358181, 18.64970105, 10.79617637,
        6.29225389,  9.16325497, 14.35105679,  5.3585295 , 13.10951908,
       13.99575946,  2.96412781,  9.27029192,  8.24011926,  8.50172421,
       14.28865322,  0.12125   , 10.85255309, 15.47287752,  0.23666667,
       13.24020606,  9.26794755, 11.05057255,  5.66223799,  2.44908136,
        8.36806921,  9.06289511, 18.19536339, 18.70648211, 14.17300813,
       13.22060134, 11.62643124,  5.23942599, 10.083221  , 10.89647924,
        7.5678207 ,  9.89016891,  7.56823839,  9.38463536,  4.83711557,
        6.70313736,  4.97210132, 10.68971385,  5.47290643,  9.19100967,
       18.27565043,  4.16600344,  7.0985486 , 15.45509886])

In [46]:
mse = mean_squared_error(y_pred,y_test)
np.sqrt(mse)

np.float64(1.603921005581593)

In [47]:
joblib.dump(model,"model.pkl")

['model.pkl']